# Generated by Django 6.0.3 on 2026-04-07 14:55

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.models.gerar_token, max_length=64, unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('cpf_pix', models.CharField(blank=True, default='', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=False)),
                ('acesso_ate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('operacional', 'Operacional'), ('material', 'Material'), ('servico', 'Serviço'), ('pessoal', 'Pessoal'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='core.cliente')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(default='un', max_length=50)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='core.cliente')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('mp_preference_id', models.CharField(blank=True, default='', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, default='')),
                ('qr_code_base64', models.TextField(blank=True, default='')),
                ('pix_copia_cola', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_vendida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('outro', 'Outro')], default='dinheiro', max_length=20)),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=200)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.cliente')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.insumo')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
